import './globals.css'
import '../../public/css/style.css';
import '../../public/css/toastr.min.css';
import '../../public/css/calendar.css';


import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'
import { Providers } from "@/redux/provider";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Providers >
        <Header />
          {children}
        <Footer />
      </Providers >
      </body>
    </html>
  );
}
