

export const REPORT_TYPE = [
  {"ARMED ATTACK" : "ARMD"},
  {"BANDITRY" : "BAND"},
  {"BOUNDARY DISPUTE": "BOUD"},
  {"COMMUNITY AGGRESSION": "COMM"},
  {"CROSS BORDER CONFLICT": "CROS"},
  {"DESTRUCTION OF PROPERTY": "DEST"},
  {"INTER ETHNIC DISPUTE": "INTER"},
  {"LAND DISPUTE": "LAND"},
  {"POLITICAL": "POLI"},
  {"PROTEST": "PROT"},
  {"RESOURCE CONFLICT": "RESC"},
  {"STOCK THEFT": "STOC"},
  {"TERRORISM": "TERR"},
  {"OTHER": "OTHR"},
  {"RAPE & GENDER BASED VIOLENCE": "GEND"},
]