const THIS_MONTH = 'month';
const REJECTED = 'REJECTED';
const ESCALATED = 'ESCALATED';
const CANCELED = 'CANCELED';
const RECURRING_CANCELED = 'RECURRING_CANCELED';
const VERIFICATION_REQUIRED = 'VERIFICATION_REQUIRED';

export default Object.freeze({
  THIS_MONTH,
  ESCALATED,
  REJECTED,
  CANCELED,
  RECURRING_CANCELED,
  VERIFICATION_REQUIRED
});