export const kadunaWards = [
  {lga: 'Igabi', ward: 'Rigasa'},
  {lga: 'Igabi', ward: 'Afaka'},
  {lga: 'Igabi', ward: 'Rigachikun'},
  {lga: 'Kaduna South', ward: 'Tudun Wada South'},
  {lga: 'Kaduna South', ward: 'Kakuri Gwari'},
  {lga: 'Kaduna South', ward: 'Badiko'},
  {lga: 'Kauru', ward: 'Badurum'},
  {lga: 'Kauru', ward: 'Damakasuwa'},
  {lga: 'Kauru', ward: 'Kamaru'},
  {lga: 'Sabon-Gari', ward: 'Samaru'},
  {lga: 'Sabon-Gari', ward: 'Jama A'},
  {lga: 'Sabon-Gari', ward: 'Chikaji'},
  {lga: 'Sabon-Gari', ward: 'Jushi'},
  {lga: 'Sabon-Gari', ward: 'Hanwa'},
  {lga: 'Zangon-Kataf', ward: 'Unguwar Gaya'},
  {lga: 'Zangon-Kataf', ward: 'Zango Urban'},
  {lga: 'Zangon-Kataf', ward: 'Zaman Dabo'},
]

export const josWards = [
  {lga: 'Jos-North ', ward: 'Naraguta B'},
  {lga: 'Jos-North ', ward: 'Abba Nashehu'},
  {lga: 'Jos-North ', ward: 'Ali Kazaure'},
  {lga: 'Jos-North ', ward: 'Jos Jarawa '},
  {lga: 'Jos-North ', ward: 'Naraguta A '},
  {lga: 'Jos-North ', ward: 'Jos Jarawa'},
  {lga: 'Mangu', ward: 'Panyam South'},
  {lga: 'Mangu', ward: 'Mangu Halle'},
  {lga: 'Mangu', ward: 'Kadunu'},
  {lga: 'Mangu', ward: 'Kombun'},
  {lga: 'Mangu', ward: 'Mangu II'},
  {lga: 'Jos-South', ward: 'Bukuru'},
  {lga: 'Jos-South', ward: 'Gyel A'},
  {lga: 'Jos-South', ward: 'Zawan A'},
  {lga: 'Jos-South', ward: 'Gyel A'},
  {lga: 'Jos-South', ward: 'Zawan A'},
  {lga: 'Jos-South', ward: 'Zawan B'},
  {lga: 'Jos-South', ward: 'Shen'},
  {lga: 'Jos-South', ward: 'Zawan B'},
]